apex_football/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path
from main.views import show_index, show_products_by_xml, show_products_by_json, show_product_xml_by_id, show_product_json_by_id, create_product, show_product, login_user, register_user, logout_user, edit_product_request, delete_product_request

app_name = 'main'

urlpatterns = [
    path('', show_index, name='show_index'),
    path('create_product', create_product, name='create_product'),
    path('show_product/<str:id>/', show_product, name='show_product'),
    path('xml', show_products_by_xml, name='show_products_by_xml'),
    path('json', show_products_by_json, name='show_products_by_json'),
    path('xml/<str:id>/', show_product_xml_by_id, name='show_product_xml_by_id'),
    path('json/<str:id>/', show_product_json_by_id, name='show_product_json_by_id'),
    path('login/', login_user, name="login"),
    path('register/', register_user, name="register"),
    path('logout/', logout_user, name="logout"),
    path('show_product/<uuid:id>/edit', edit_product_request, name='edit_product_request'),
    path('show_product/<uuid:id>/delete', delete_product_request, name='delete_product_request'),
]

main/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator


class Product(models.Model):
    CATEGORIES = [
        ('FW', 'Footwear'),
        ('Sh', 'Shirts'),
        ('misc', 'Misc'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    requester = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=255)
    price = models.IntegerField(default=0, validators=[
        MinValueValidator(0),
    ])
    description = models.TextField(max_length=1000)
    thumbnail = models.URLField(blank=True, null=True)
    category = models.CharField(max_length=20, choices=CATEGORIES, default='FW')
    is_featured = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)

    def __str__(self):
        return self.name

main/forms.py
from django import forms
from django.forms import ModelForm
from main.models import Product


class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description", "category", "thumbnail"]
        widgets = {
            "name": forms.widgets.TextInput(attrs={'class': 'form-control'}),
            "price": forms.widgets.NumberInput(attrs={'class': 'form-control', 'min': '0'}),
            "description": forms.widgets.TextInput(attrs={'class': 'form-control'}),
            "thumbnail": forms.widgets.URLInput(attrs={'class': 'form-control'}),
            "category": forms.widgets.Select(attrs={'class': 'form-select'}),
        }


form = ProductForm()
for field in form:
    field.field.widget.attrs

main/views.py
import datetime
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from main.models import Product
from main.forms import ProductForm
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.core import serializers


def show_products_by_xml(request):
    product_list = Product.objects.all()
    xml_data = serializers.serialize("xml", product_list)
    return HttpResponse(xml_data, content_type="application/xml")


def show_products_by_json(request):
    product_list = Product.objects.all()
    json_data = serializers.serialize("json", product_list)
    return HttpResponse(json_data, content_type="application/json")


def show_product_xml_by_id(request, id):
    product_item = get_object_or_404(Product, id=id)
    xml_data = serializers.serialize("xml", [product_item])
    return HttpResponse(xml_data, content_type="application/xml")


def show_product_json_by_id(request, id):
    product_item = get_object_or_404(Product, id=id)
    json_data = serializers.serialize("json", [product_item])
    return HttpResponse(json_data, content_type="application/json")


@login_required(login_url='/login')
def show_product(request, id):
    product = get_object_or_404(Product, id=id)
    return render(
        request,
        "product_detail.html",
        {
            "product": product
        }
    )


@login_required(login_url='/login')
def create_product(request):
    form = ProductForm(request.POST or None)
    if form.is_valid() and request.method == "POST":
        product_entry = form.save(commit=False)
        product_entry.requester = request.user
        product_entry.save()
        return redirect('main:show_index')

    context = {'form': form}
    return render(request, "create_product.html", context)


@login_required(login_url='/login')
def show_index(request):
    filter_type = request.GET.get("filter", "all")
    if filter_type == "all":
        product_list = Product.objects.all()
    else:
        product_list = Product.objects.filter(requester=request.user)
    return render(
        request,
        "index.html",
        {
            "nama": "Christopher Evan Tanuwidjaja",
            "kelas": "A",
            "app_name": "main",
            "username": request.user.username,
            "product_list": product_list,
            "last_login": request.COOKIES.get('last_login', 'Never')
        }
    )


def register_user(request):
    form = UserCreationForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form': form}
    return render(request, 'register.html', context)


def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_index"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
    else:
        form = AuthenticationForm(request)
    context = {'form': form}
    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    return redirect('main:login')


@login_required(login_url='/login')
def edit_product_request(request, id):
    product = get_object_or_404(Product, pk=id)
    if product.requester != request.user:
        return HttpResponse(status=401)
    form = ProductForm(request.POST or None, instance=product)
    if form.is_valid() and request.method == "POST":
        form.save()
        return redirect('main:show_index')
    return render(
        request,
        "edit_product_request.html",
        {
            'form': form,
        }
    )


@login_required(login_url='/login')
def delete_product_request(request, id):
    product = get_object_or_404(Product, pk=id)
    if product.requester != request.user:
        return HttpResponse(status=401)
    product.delete()
    return HttpResponseRedirect(reverse('main:show_index'))

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
        {% block meta %}
        {% endblock meta %}
    <body>
        {% block content %}
        {% endblock content %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    </body>
</html>

main/templates/create_product.html
{% extends 'base.html' %} 
{% block content %}
<h1>Add Product</h1>

<form method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
    <tr>
      <td></td>
      <td>
        <input type="submit" value="Add PRODUCT" />
      </td>
    </tr>
  </table>
</form>

{% endblock %}

main/templates/edit_product_request.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container mt-5">
        <div class="mb-3">
        <a href="{% url 'main:show_index' %}" class="btn btn-outline-secondary">
            <i class="bi bi-arrow-left"></i> Back to Product List
        </a>
    </div>
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card p-4">
                    <h1 class="text-center mb-4">Edit Product Request</h1>
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="mb-3 form-group">
                                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                {{ field.as_widget }}
                            </div>
                        {% endfor %}
                        {% if field.errors %}
                            <div class="invalid-feedback d-block">
                                {% for error in field.errors %}{{ error }}{% endfor %}
                            </div>
                        {% endif %}
                        <div class="d-grid gap-2">
                            <input class="btn btn-primary" type="submit" value="Create" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

main/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    {% include "navbar.html" %}
    <div class="container-lg my-4 mx-2 mx-lg-auto w-auto p-2 border border-2 rounded d-flex">
        <a href="?filter=all" class="btn btn-secondary me-2">All Requests</a>
        <a href="?filter=my" class="btn btn-secondary">My Requests</a>
    </div>
    {% if not product_list %}
        <div class="container d-flex flex-column align-items-center mx-auto">
            <p>Belum ada data produk pada Apex Football</p>
            <img src="{% static "image/no_product_found.png" %}" alt="ProductNotFound">
        </div>
    {% else %}
        <div class="container-lg d-flex flex-wrap p-3 my-4 mx-2 mx-lg-auto w-auto gap-3">
            {% for product in product_list %}
                <div class="card" style="width: 18rem;">
                    {% if product.thumbnail %}
                        <img src="{{ product.thumbnail }}"
                             alt="thumbnail"
                             width="150"
                             height="100"
                             class="card-img-top">
                    {% else %}
                        <img src="{% static 'image/no_product_thumbnail.png' %}"
                             alt="thumbnail"
                             width="150"
                             height="100"
                             class="card-img-top">
                    {% endif %}
                    <div class="card-body">
                        <h3 class="card-title">{{ product.name }}</h3>
                        <span class="badge bg-primary">{{ product.get_category_display }}</span>
                        {% if product.is_featured %}<span class="badge bg-warning text-dark">Featured</span>{% endif %}
                        {% if product.is_verified %}<span class="badge bg-success">Verified</span>{% endif %}
                        {% if product.requester %}
                            <p>Requester: {{ product.requester.username }}</p>
                        {% else %}
                            <p>Requester: Anonymous</p>
                        {% endif %}
                        Price: {{ product.price }}
                    </p>
                    <p class="card-text">{{ product.description|truncatewords:25 }}...</p>
                    <div class="d-flex justify-content-between">
                        <a class="btn btn-secondary btn-sm"
                           href="{% url 'main:show_product' product.id %}">Read More</a>
                        {% if user.is_authenticated and product.requester == user %}
                            <a class="btn btn-warning btn-sm"
                               data-bs-toggle="modal"
                               data-bs-target="#editModal{{ product.id }}">Edit</a>
                            <a class="btn btn-danger btn-sm"
                               data-bs-toggle="modal"
                               data-bs-target="#deleteModal{{ product.id }}">Delete</a>
                            <div class="modal fade"
                                 id="editModal{{ product.id }}"
                                 tabindex="-1"
                                 aria-labelledby="editModalHeader{{ product.id }}"
                                 aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h1 class="modal-title fs-5" id="editModalHeader{{ product.id }}">Edit Product Request</h1>
                                            <button type="button"
                                                    class="btn-close"
                                                    data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">Do you want to edit current product request?</div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                            <a type="button"
                                               href="{% url 'main:edit_product_request' product.id %}"
                                               class="btn btn-warning">Edit</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal fade"
                                 id="deleteModal{{ product.id }}"
                                 tabindex="-1"
                                 aria-labelledby="deleteModalHeader{{ product.id }}"
                                 aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h1 class="modal-title fs-5" id="deleteModalHeader{{ product.id }}">Delete Product Request</h1>
                                            <button type="button"
                                                    class="btn-close"
                                                    data-bs-dismiss="modal"
                                                    aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">Do you want to delete current product request?</div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                            <a type="button"
                                               href="{% url 'main:delete_product_request' product.id %}"
                                               class="btn btn-danger">Delete</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <hr>
        {% endfor %}
    {% endif %}
</div>
{% endblock content %}

main/templates/login.html
{% extends "base.html" %}
{% block meta %}
    <title>Login</title>
{% endblock meta %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card p-4">
                    <h1 class="text-center mb-4">Login</h1>
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="mb-3">
                                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                <input type="{{ field.field.widget.input_type }}"
                                       name="{{ field.name }}"
                                       id="{{ field.id_for_label }}"
                                       class="form-control"
                                       placeholder="{{ field.label }}"
                                       required>
                                {% if field.errors %}
                                    <div class="invalid-feedback d-block">
                                        {% for error in field.errors %}{{ error }}{% endfor %}
                                    </div>
                                {% endif %}
                                {% if field.help_text %}<div class="form-text">{{ field.help_text }}</div>{% endif %}
                            </div>
                        {% endfor %}
                        <div class="d-grid gap-2">
                            <input class="btn btn-primary login_btn" type="submit" value="Login" />
                        </div>
                    </form>
                    <p class="text-center mt-3">
                        Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

main/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-dark fg-light" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:show_index' %}">
            <img src="{% static 'image/logo.png' %}"
                 alt="Apex Football"
                 class="d-inline-block"
                 width="156"
                 height="128">
        </a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNav"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse"
             id="navbarNav">
            <ul class="navbar-nav justify-content-center mx-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:show_index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:create_product' %}">Create Product Request</a>
                </li>
            </ul>
            <div class="nav-item d-flex align-items-center hover-bg-light">
                <div class="me-3 text-start text-lg-end">
                    <div class="text-muted">Christopher Evan Tanuwidjaja</div>
                    <small class="text-muted">PBP A - 2406358056</small>
                    <small class="text-muted d-block">Application main (Apex Football)</small>
                </div>
            </div>
            <ul class="navbar-nav justify-content-end">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle"
                       href="#"
                       id="navbarDropdown"
                       role="button"
                       data-bs-toggle="dropdown"
                       aria-expanded="false">{{ user.username }}</a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li>
                            <p class="dropdown-item">Sesi terakhir login : {{ last_login|default:"Never" }}</p>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'main:logout' %}">Logout</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

main/templates/product_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5">
    <div class="mb-3">
        <a href="{% url 'main:show_index' %}" class="btn btn-outline-secondary">
            <i class="bi bi-arrow-left"></i> Back to Product List
        </a>
    </div>

    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <div class="card shadow-sm">
                <div class="card-body">
                    <div class="row">
                        {% if product.thumbnail %}
                        <div class="col-md-4 mb-3 mb-md-0 d-flex justify-content-center align-items-center">
                            <img src="{{ product.thumbnail }}" class="img-fluid rounded-start" alt="Product thumbnail">
                        </div>
                        {% endif %}
                        <div class="{% if product.thumbnail %}col-md-8{% else %}col-12{% endif %}">
                            <h1 class="card-title">{{ product.name }}</h1>
                            <p class="card-subtitle text-muted mb-2">
                                Requester: {% if product.requester %}
                                {{ product.requester.username }}
                                {% else %}
                                Anonymous
                                {% endif %}
                            </p>
                            <hr>
                            <p class="card-text">
                                <span class="badge bg-primary">{{ product.get_category_display }}</span>
                                {% if product.is_featured %}
                                <span class="badge bg-warning text-dark">Featured</span>
                                {% endif %}
                                {% if product.is_verified %}
                                <span class="badge bg-success">Verified</span>
                                {% endif %}
                            </p>
                            <p class="card-text fs-4 text-success fw-bold">Price: ${{ product.price }}</p>
                            <hr>
                            <p class="card-text">{{ product.description }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

main/templates/register.html
{% extends "base.html" %}
{% block meta %}
    <title>Register</title>
{% endblock meta %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h1 class="card-title text-center mb-4">Register</h1>
                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="mb-3">
                                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                    {{ field }}
                                    {% if field.help_text %}
                                        <div class="form-text">{{ field.help_text }}</div>
                                    {% endif %}
                                    {% for error in field.errors %}
                                        <div class="text-danger">{{ error }}</div>
                                    {% endfor %}
                                </div>
                            {% endfor %}
                            <div class="d-grid gap-2">
                                <button type="submit" class="btn btn-primary" name="submit">Daftar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}